[package]
name = "my-php-app"
version = "0.1.0"

[dependencies]
"php/php" = "=8.3.4"
 
[fs]
"/app/" = "."
 
[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-t", "/app/", "-S", "localhost:8080"]